In [ ]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

In [1]:
import numpy as np
np.__version__

'1.23.5'

In [2]:
L = list(range(21))
L

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [3]:
[str(c) for c in L]

['0',
 '1',
 '2',
 '3',
 '4',
 '5',
 '6',
 '7',
 '8',
 '9',
 '10',
 '11',
 '12',
 '13',
 '14',
 '15',
 '16',
 '17',
 '18',
 '19',
 '20']

In [4]:
[type(item) for item in L]

[int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int,
 int]

In [5]:
np.zeros(10, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [6]:
np.ones((3,8), dtype=float)

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [7]:
np.full((3,5),1.23)

array([[1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23],
       [1.23, 1.23, 1.23, 1.23, 1.23]])

In [8]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [10]:
np.random.normal(0, 1, (3,3))

array([[-0.12657884, -0.82743964, -0.39925652],
       [ 0.12845014,  2.67494026,  1.50832855],
       [ 0.10444345, -0.76129837,  0.49684035]])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.random.seed(0)


x1 = np.random.randint(10, size=4) #one dimension
x2 = np.random.randint(10, size=(3,5)) #two dimension
x3 = np.random.randint(10, size=(3,5,5)) #three dimension


print("x1 ndim:", x1.ndim)
print("x1 shape:", x1.shape)
print("x1 size: ", x1.size)

x1 ndim: 1
x1 shape: (4,)
x1 size:  4


In [13]:
print("x2 ndim:", x2.ndim)
print("x2 shape:", x2.shape)
print("x2 size: ", x2.size)

x2 ndim: 2
x2 shape: (3, 5)
x2 size:  15


In [14]:
print("x3 ndim:", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim: 3
x3 shape: (3, 5, 5)
x3 size:  75


In [15]:
x1 = np.array([4, 3, 4, 4, 8, 4])
x1

array([4, 3, 4, 4, 8, 4])

In [16]:
x1[0]

4

In [17]:
x1[4]

8

In [18]:
x1[-1]

4

In [19]:
x2=np.array([[3, 7, 5, 5],[0, 1, 5, 9],[3, 0, 5, 0]])
x2

array([[3, 7, 5, 5],
       [0, 1, 5, 9],
       [3, 0, 5, 0]])

In [20]:
x2[2,-1]

0

In [21]:
x2[0,0] = 12
x2

array([[12,  7,  5,  5],
       [ 0,  1,  5,  9],
       [ 3,  0,  5,  0]])

In [22]:
x = np.arange(20)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [23]:
x[:5]

array([0, 1, 2, 3, 4])

In [24]:
x[4:]

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [25]:
x[4:7]

array([4, 5, 6])

In [26]:
x[ : : 2]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [27]:
x[::-1]

array([19, 18, 17, 16, 15, 14, 13, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,
        2,  1,  0])

In [28]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
z = [21,21,21]
np.concatenate([x, y,z])

array([ 1,  2,  3,  3,  2,  1, 21, 21, 21])

In [30]:
grid = np.array([[1,2,3],[4,5,6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [31]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [32]:
x = np.array([3,4,5])
grid = np.array([[1,2,3],[17,18,19]])
np.vstack([x,grid])

array([[ 3,  4,  5],
       [ 1,  2,  3],
       [17, 18, 19]])

In [33]:
z = np.array([[9],[9]])
np.hstack([grid,z])

array([[ 1,  2,  3,  9],
       [17, 18, 19,  9]])

Pandas

In [34]:
import pandas as pd

In [35]:
data = pd.DataFrame({'Country': ['India','Nepal','Pakistan','Bangladesh','Bhutan'],
                    'Rank':[11,40,100,130,101]})
data

Country  Rank
0       India    11
1       Nepal    40
2    Pakistan   100
3  Bangladesh   130
4      Bhutan   101

In [36]:
data.describe()

Rank
count    5.000000
mean    76.400000
std     49.084621
min     11.000000
25%     40.000000
50%    100.000000
75%    101.000000
max    130.000000

In [38]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype 
---  ------   --------------  ----- 
 0   Country  5 non-null      object
 1   Rank     5 non-null      int64 
dtypes: int64(1), object(1)
memory usage: 208.0+ bytes


In [39]:
data = pd.DataFrame({'group':['x', 'x', 'x', 'y','y', 'y', 'z', 'z','z'],'ounces':[4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

group  ounces
0     x     4.0
1     x     3.0
2     x    12.0
3     y     6.0
4     y     7.5
5     y     8.0
6     z     3.0
7     z     5.0
8     z     6.0

In [40]:
data.sort_values(by=['ounces'],ascending=True,inplace=False)

group  ounces
1     x     3.0
6     z     3.0
0     x     4.0
7     z     5.0
3     y     6.0
8     z     6.0
4     y     7.5
5     y     8.0
2     x    12.0

In [41]:
data.sort_values(by=['group','ounces'],ascending=[True,False],inplace=False)

group  ounces
2     x    12.0
0     x     4.0
1     x     3.0
5     y     8.0
4     y     7.5
3     y     6.0
8     z     6.0
7     z     5.0
6     z     3.0

In [42]:
data = pd.DataFrame({'k1':['one']*3 + ['two']*4, 'k2':[3,2,1,3,3,4,4]})
data

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
4  two   3
5  two   4
6  two   4

In [43]:
data.sort_values(by='k2')

k1  k2
2  one   1
1  one   2
0  one   3
3  two   3
4  two   3
5  two   4
6  two   4

In [44]:
data.drop_duplicates()

k1  k2
0  one   3
1  one   2
2  one   1
3  two   3
5  two   4

In [45]:
data = pd.DataFrame({'food': ['bacon', 'pulled pork', 'bacon', 'Pastrami','corned beef', 'Bacon', 'pastrami', 'honey ham','nova lox'],
                 'ounces': [4, 3, 12, 6, 7.5, 8, 3, 5, 6]})
data

food  ounces
0        bacon     4.0
1  pulled pork     3.0
2        bacon    12.0
3     Pastrami     6.0
4  corned beef     7.5
5        Bacon     8.0
6     pastrami     3.0
7    honey ham     5.0
8     nova lox     6.0

In [46]:
data.assign(new_variable = data['ounces']*14)

food  ounces  new_variable
0        bacon     4.0          56.0
1  pulled pork     3.0          42.0
2        bacon    12.0         168.0
3     Pastrami     6.0          84.0
4  corned beef     7.5         105.0
5        Bacon     8.0         112.0
6     pastrami     3.0          42.0
7    honey ham     5.0          70.0
8     nova lox     6.0          84.0

In [48]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data

0       1.0
1    -999.0
2       2.0
3    -999.0
4   -1000.0
5       3.0
dtype: float64

In [49]:
data = pd.Series([1., -999., 2., -999., -1000., 3.])
data.replace([-999,-1000],np.nan,inplace=True)
data

0    1.0
1    NaN
2    2.0
3    NaN
4    NaN
5    3.0
dtype: float64

In [50]:
data = pd.DataFrame(np.arange(12).reshape((3, 4)),index=['Ohio', 'Colorado', 'New York'],columns=['one', 'two', 'three', 'four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
New York    8    9     10    11

In [53]:
ages = [20, 22, 25, 27, 21, 23, 37, 31, 61, 45, 41, 32]
bins = [18, 25, 35, 60, 100]
cats = pd.cut(ages, bins)
cats

[(18, 25], (18, 25], (18, 25], (25, 35], (18, 25], ..., (25, 35], (60, 100], (35, 60], (35, 60], (25, 35]]
Length: 12
Categories (4, interval[int64, right]): [(18, 25] < (25, 35] < (35, 60] < (60, 100]]

In [54]:
pd.cut(ages,bins,right=False)

[[18, 25), [18, 25), [25, 35), [25, 35), [18, 25), ..., [25, 35), [60, 100), [35, 60), [35, 60), [25, 35)]
Length: 12
Categories (4, interval[int64, left]): [[18, 25) < [25, 35) < [35, 60) < [60, 100)]

In [55]:
pd.value_counts(cats)

(18, 25]     5
(25, 35]     3
(35, 60]     3
(60, 100]    1
Name: count, dtype: int64

In [56]:
bin_names = ['Youth', 'YoungAdult', 'MiddleAge', 'Senior']
new_cats = pd.cut(ages, bins,labels=bin_names)

pd.value_counts(new_cats)

Youth         5
YoungAdult    3
MiddleAge     3
Senior        1
Name: count, dtype: int64

In [58]:
pd.value_counts(new_cats).cumsum()

Youth          5
YoungAdult     8
MiddleAge     11
Senior        12
Name: count, dtype: int64

In [59]:
df = pd.DataFrame({'key1' : ['a', 'a', 'b', 'b', 'a'],
                   'key2' : ['one', 'two', 'one', 'two', 'one'],
                   'data1' : np.random.randn(5),
                   'data2' : np.random.randn(5)})
df

key1 key2     data1     data2
0    a  one  1.509445 -0.038224
1    a  two  1.067775  0.367974
2    b  one -0.686589 -0.044724
3    b  two  0.014873 -0.302375
4    a  one -0.375666 -2.224404

In [60]:
grouped = df['data1'].groupby(df['key1'])
grouped.mean()

key1
a    0.733851
b   -0.335858
Name: data1, dtype: float64

In [61]:
dates = pd.date_range('20130101',periods=6)
df = pd.DataFrame(np.random.randn(6,4),index=dates,columns=list('ABCD'))
df

A         B         C         D
2013-01-01  0.724006  0.359003  1.076121  0.192141
2013-01-02  0.852926  0.018357  0.428304  0.996278
2013-01-03 -0.491150  0.712678  1.113340 -2.153675
2013-01-04 -0.416111 -1.070897  0.221139 -1.123057
2013-01-05 -1.050758  1.012079  1.543716 -0.402115
2013-01-06  0.864749 -0.226869  0.811160  0.287795

In [62]:
df[:3]

A         B         C         D
2013-01-01  0.724006  0.359003  1.076121  0.192141
2013-01-02  0.852926  0.018357  0.428304  0.996278
2013-01-03 -0.491150  0.712678  1.113340 -2.153675

In [63]:
df['20130101':'20130104']

A         B         C         D
2013-01-01  0.724006  0.359003  1.076121  0.192141
2013-01-02  0.852926  0.018357  0.428304  0.996278
2013-01-03 -0.491150  0.712678  1.113340 -2.153675
2013-01-04 -0.416111 -1.070897  0.221139 -1.123057